---
# Run once
- name: "[ xwiki_install_mariadb ]"
  include_tasks: xwiki_install_mariadb.yaml
  tags: xwiki_install_mariadb
  
- name: "[xwiki_download_war]"
  include_tasks: xwiki_download_war.yaml
  tags: xwiki_download_war

# Run for every instance
- name: "[xwiki_instance_data_dir]"
  include_tasks: xwiki_instance_data_dir.yaml
  tags: xwiki_instance_data_dir
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"

- name: "[xwiki_instance_unpack_war]"
  include_tasks: xwiki_instance_unpack_war.yaml
  tags: xwiki_instance_unpack_war  
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"

- name: "[xwiki_instance_jdbc_driver]"
  include_tasks: xwiki_instance_jdbc_driver.yaml
  tags: xwiki_instance_jdbc_driver
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"
 
- name: "[xwiki_instance_configs]"
  include_tasks: xwiki_instance_configs.yaml
  tags: xwiki_instance_configs
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"

- name: "[ xwiki_instance_db ]"
  include_tasks: 
    file: xwiki_instance_db.yaml
    apply:
      tags:
        - xwiki_instance_db
  tags: xwiki_instance_db
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"
