---
- name: [ xwiki_install_mariadb ]
  import_tasks: xwiki_install-mariadb.yaml
  tags: xwiki_install_mariadb
  
- name: Download xwiki WAR
  import_tasks: xwiki_download_war.yaml
  tags: xwiki_download_war

- name: Unpack xwiki WAR
  import_tasks: xwiki_unpack_war.yaml
  tags: xwiki_unpack_war

- name: Create and configure xwiki data dir
  import_tasks: xwiki_data_dir.yaml
  tags: xwiki_data_dir

- name: Install jdbc driver
  import_tasks: xwiki_jdbc_driver.yaml
  tags: xwiki_jdbc_driver
 
- name: [xwiki_instance_configs]
  import_tasks: xwiki_instance_configs.yaml
  tags: xwiki_instance_configs
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"
  
- name: [ xwiki_instance_db ]
  import_tasks: xwiki_instance_db.yaml
  tags: xwiki_install_mariadb
  loop: "{{ instances }}"
  loop_control:
    label: "{{ item.instance }}"


