---
- name: Download xwiki WAR
  import_tasks: xwiki_download_war.yaml
  tags: xwiki_download_war

- name: Unpack xwiki WAR
  import_tasks: xwiki_unpack_war.yaml
  tags: xwiki_unpack_war

- name: Create and configure xwiki data dir
  import_tasks: xwiki_data_dir.yaml
  tags: xwiki_data_dir

- name: Install jdbc driver
  import_tasks: xwiki_jdbc_driver.yaml
  tags: xwiki_jdbc_driver
 
- name: Create configs
  import_tasks: xwiki_configs.yaml
  tags: xwiki_configs

- name: Install MaraiDB and create Database
  import_tasks: xwiki_mariadb.yaml
  tags: xwiki_mariadb
