---
- name: [xwiki_instance_jdbc_driver] - Install JDBC driver
  get_url:
    url: "{{xwiki_jdbc_dwnldurl}}"
    dest: "{{xwiki_webapp}}/WEB-INF/lib"
    owner: "{{xwiki_tomcat_instance}}"
    group: "{{xwiki_tomcat_instance}}"
