---
- name: "Create {{xwiki_webapp}}"
  file:
    path: "{{xwiki_webapp}}"
    state: directory
    owner: "{{ tomcat_instance }}"
    group: "{{ tomcat_instance }}"

- name: Unapck xwiki WAR
  unarchive:
    src: "/tmp/{{xwiki_archive}}"
    dest: "{{xwiki_webapp}}"
    remote_src: yes
    owner: "{{ tomcat_instance }}"
    group: "{{ tomcat_instance }}"
    creates: "{{xwiki_webapp}}/WEB-INF"
