---
- name: [xwiki_configs] - Create config files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{xwiki_tomcat_instance}}"
    group: "{{xwiki_tomcat_instance}}"
    mode: '0440'
  with_items:
    - src: xwiki.properties.j2
      dest: "{{xwiki_webapp}}/WEB-INF/xwiki.properties"
    - src: hibernate.cfg.xml.j2
      dest: "{{xwiki_webapp}}/WEB-INF/hibernate.cfg.xml"
    - src: xwiki.cfg.j2
      dest: "{{xwiki_webapp}}/WEB-INF/xwiki.cfg"
      
